return {
  dap = {
    breakpoint = "",
    conditional_breakpoint = "",
    rejected_breakpoint = "",
    log_point = "",
  },
  diagnostics = {
    error = "",
    warning = "",
    info = "",
    hint = "",
  },
  ui = {
    close = "",
    modified = "●",
    fold_closed = "",
    fold_open = "",
    tab_separator_left = "",
    tab_separator_right = "",
    segment_separator_left = "",
    segment_separator_right = "",
  },
  misc = {
    chevron_down = "",
    chevron_left = "",
    chevron_right = "",
    chevron_up = "",
    arrow_down = "",
    arrow_left = "",
    arrow_right = "",
    arrow_up = "",
    arrow_circle_up = "",
    arrow_circle_left = "",
    arrow_circle_right = "",
    arrow_circle_down = "",
    center_dot = "·",
    slant_top_right = "",
    slant_bottom_right = "",
    slant_bottom_left = "",
    slant_top_left = "",
  },
}
